function [out] = mcm_mgmt_ini
%%% List of all sites (Change here to manually alter site list:):
out.site_list = {'TP39';'TP74';'TP89';'TP02';'TP_PPT';'MCM_WX'; 'TPD';'TPAg'; 'TP_VDT'};

%%% List of all data types (Change here to manually alter site list:):
out.type_list = {'general';'met';'chamber';'CPEC';'OPEC';'sapflow';'trenched';'OTT';'NRL';'WX'; 'TP_PPT';'PPT'};


%%% Cell array that links a given site to the data types that are available
%%% at that site
out.types_available = {... 
'TP39', [1:9]; ... % TP39 has all types of data available:
'TP74', [1:2 4:6];... % TP74 has most types of data available: 
'TP89', [1:2 5];... % TP89 has some types of data available: 
'TP02', [1:2 4:5];... % TP02 has some types of data available: 
'TP_PPT', [11];... % TP_PPT has some types of data available: 
'MCM_WX', [10];... % MCM_WX has some types of data available: 
'TPD', [1:2 4 12];... % MCM_WX has some types of data available: 
'TPAg', [1:2 4]; ... 
'TP_VDT', [1:2 4]; ... 
};

out.proc_list = {...
    'Extract Data'                  ,'mcm_extract_main(site, data_type, year);';...    % 1
    'Quickplot Variables'           ,'mcm_quickplot_main(year, site, data_type);';...
    'Clean Met Data'                ,'mcm_metclean(year, site,data_type);';...
    'Edit Met Fixer File'           ,'edit mcm_metfixer;';...
    'Run Met Fixer File'            ,'mcm_metfixer(year, site, data_type);';...        % 5
    'Fill met variables'            ,'mcm_metfill_main(year, site);';...
    'Calculate Soil Heat Flux'      ,'mcm_SHF(year, site);';...
    'Check for Completeness'        ,'mcm_checkfiles(site, year,data_type);';...
    'Recalculate Fluxes From HF'    ,'mcm_calc_fluxes(site, data_type);';...
    'Put Fluxes into Annual Files'  ,'mcm_mat2annual_main(year, site, data_type);';... % 10
    'Clean Fluxes'                  ,'mcm_fluxclean_main(year, site,data_type);';
    'Edit Flux Fixer File'          ,'mcm_fluxfixer_main(year, ''edit'', data_type);';...
    'Run Flux Fixer File'           ,'mcm_fluxfixer_main(year, site, data_type);';...
    'Storage & NEE Calc, Clean'     ,'mcm_CPEC_storage(year, site);';...
    'First Compile'                 ,'mcm_data_compiler([],site,data_type,1);';...     % 15
    'Run Footprint Models'          ,'run_mcm_footprint(site,[],1);';...   
    'Edit LE, H Gapfilling Defaults','mcm_edit_gapfilling_defaults(''LE'');';...   
    'Run LE, H Gapfilling'          ,'mcm_Gapfill_LE_H_default(site,[],1);';...   
    'Edit NEE Gapfilling Defaults'  ,'mcm_edit_gapfilling_defaults(''NEE'');';...   
    'Run NEE Gapfilling'            ,'mcm_Gapfill_NEE_default(site,[],1);';...            % 20
    'Compile All'                   ,'mcm_data_compiler([],site,data_type,2);';...    
    'Final Data Check'              ,'mcm_check_master(site);';...   
    'Fish Hatchery Output'          ,'mcm_output_FHdata(year);';...   
    'CCP Output'                    ,'mcm_CCP_output([],site,[],[]);';...              
    'Run Sapflow Calculations'      ,'mcm_sapflow_calc(year,site);';...                % 25
    'Fluxnet Output'                ,'mcm_fluxnet_output(year,site);';...
    %     'MCM_WX Output'                 ,'mcm_output_wxstn(year)';
    };

%%% Here, the values assigned correspond to the rows of processes outlined
%%% above. 
out.procs_available = { ...
'general'   ,[15:24 26];...    
'met'       ,[1:7];...
'chamber'   ,[1:2  8:13];...
'CPEC'      ,[1 9:10 8 2 11:14];... %'CPEC'      ,[1:2  8:14];...
'OPEC'      ,[11:13];...
'sapflow'   ,[1:5 25 21];...
'trenched'  ,[1:5];...
'OTT'       ,[1:5];... 
'NRL'       ,[1:5];... 
'WX'    ,[1:5 21 22 24];...
'TP_PPT'       ,[1:6 21 22 24];... 
'PPT'       ,[1:5];... 
};

%%%%%% Make special modifications here:



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


out.year_list = ['multiple' ;cellstr(num2str((2001:1:2025)'))];

out.extras = {...
    'Extract All Flux Data'             , 'mcm_automated_extraction(1);';...
    'Recalculate Fluxes: Last 30 Days'  , 'mcm_automated_calc_fluxes(1);';...
    'Backup All Scripts, Config, Log Files', 'mcm_documentation_compiler(1);'...
    };

% Configuration File Location:
out.config_opts = {
%     'Browse Functions', 'shell', 'unix(''thunar /1/fielddata/Matlab/Scripts'')';...
    'TPFS:  Site Parameters', 'matlab', 'edit params';...
    'TPFS:  Documentation','shell','unix(''thunar /1/fielddata/Documentation &'')';...  
    'Met:   Organization Config Files', 'shell', 'unix(''thunar /1/fielddata/Matlab/Config/Met/Organizing-Header_OutputTemplate &'');';...
    'Met:   Cleaning Thresholds', 'shell', 'unix(''thunar /1/fielddata/Matlab/Config/Met/Cleaning-Thresholds &'');';...
    'Met:   Sapflow Config Files', 'shell', 'unix(''thunar /1/fielddata/Matlab/Config/Met/Calculating-SapflowParameters &'');';...
    'Flux:  Data Inventory', 'shell','unix(''thunar /1/fielddata/Documentation/Logs/mcm_checkfiles &'');';...
    'Flux:  Calc ini Files', 'shell', 'unix(''thunar /1/fielddata/Matlab/ubc_PC_setup/Site_Specific &'');';...
    'Flux:  Site System Info', 'matlab','edit mcm_get_fluxsystem_info' ;...
    'Flux:  Gapfilling Defaults', 'matlab','mcm_edit_gapfilling_defaults' ;...
    'Flux:  Gapfilling Sums', 'shell','unix(''thunar /1/fielddata/Matlab/Data/Flux/Gapfilling &'');';...
    'BACON: MasterFile Config Files','shell','unix(''thunar /1/fielddata/Matlab/Config/Master_Files &'');';...
    'BACON: Processing Logs', 'shell', 'unix(''thunar /1/fielddata/Documentation/Logs &'');';...
    'BACON: Edit GUI Settings','matlab','edit mcm_mgmt_ini';...  
    };


%% Email recipients
out.recips = {'arainm@mcmaster.ca','jason.brodeur@gmail.com','mac.climate@gmail.com'};