function fig = view_sites()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.

load view_sites

year = datevec(now);
year = year(1);
mat3=cell(year-1999+1,1);
for i=1999:year
    mat3(i-1999+1) = {num2str(i)};
end

h0=figure(200);
set(h0,'Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'FileName','C:\NZ\MATLAB\view_sites.m', ...
	'MenuBar','none', ...
	'Name','View Sites Menu', ...
	'NumberTitle','off', ...
	'PaperPosition',[6718464 67184640 214990848 161243136], ...
	'PaperUnits','points', ...
	'Position',[0.2 0.4 0.45 0.50], ...
	'Tag','Fig1', ...
    'ToolBar','none');
    % Position [distance from left edge of window,
    %           distance from bottom edge of window,
    %           width of form,
    %           height of form]
%-------------------------------------Select site(s) and dates to view---------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[-10, 250, 300, 16], ...
	'String','Select site(s) and dates to view', ...
	'Style','text', ...
   'Tag','StaticText1');
%-------------------------------------CR-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_CR', ...
   'FontSize',10, ...
   'Max', 1, ...
	'ListboxTop',0, ...
	'Position',[20 220 58 10], ...
	'String','CR', ...
	'Style','checkbox', ...
	'Tag','CheckboxCR', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_CR', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 205 120 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','CRTraceCD', ...
   'Value',1);
% Calibration Eddy check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_CR', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 190 120 10], ...
	'String','CE', ...
	'Style','checkbox', ...
	'Tag','CRTraceCE', ...
   'Value',1);
% Calibration Profile check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_CR', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 175 120 10], ...
	'String','CP', ...
	'Style','checkbox', ...
	'Tag','CRTraceCP', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','select_CR', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 160 120 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','CRTraceEC', ...
   'Value',1);
%-------------------------------------OY-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_OY', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max',1, ...
	'Position',[70 220 58 10], ...
	'String','OY', ...
	'Style','checkbox', ...
	'Tag','CheckboxOY', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_OY', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 205 58 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','OYTraceCD', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_OY', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 190 58 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','OYTraceEC', ...
   'Value',1);
%-------------------------------------YF-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_YF', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
	'Position',[120 220 58 10], ...
	'String','YF', ...
	'Style','checkbox', ...
	'Tag','CheckboxYF', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_YF', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 205 58 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','YFTraceCD', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_YF', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 190 58 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','YFTraceEC', ...
   'Value',1);
%-------------------------------------HJP02-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_HJP02', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
	'Position',[170 220 58 10], ...
	'String','HJP02', ...
	'Style','checkbox', ...
	'Tag','CheckboxHJP02', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_HJP02', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[177 205 58 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','HJP02TraceCD', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_HJP02', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[177 190 58 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','HJP02TraceEC', ...
   'Value',1);
%-------------------------------------HJP75-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_HJP75', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
	'Position',[220 220 58 10], ...
	'String','HJP75', ...
	'Style','checkbox', ...
	'Tag','CheckboxHJP75', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_HJP75', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[227 205 58 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','HJP75TraceCD', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_HJP75', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[227 190 58 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','HJP75TraceEC', ...
   'Value',1);
%-------------------------------------PAOA-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_PAOA', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[20 140 50 10], ...
	'String','PAOA', ...
	'Style','checkbox', ...
	'Tag','CheckboxPAOA', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 125 120 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','PAOATraceCD', ...
   'Value',1);
% Calibration Eddy check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 110 58 10], ...
	'String','CE', ...
	'Style','checkbox', ...
	'Tag','PAOATraceCE', ...
   'Value',1);
% Calibration Profile check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 95 58 10], ...
	'String','CP', ...
	'Style','checkbox', ...
	'Tag','PAOATraceCP', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 80 58 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','PAOATraceEC', ...
   'Value',1);
% Calibration Chamber check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 65 58 10], ...
	'String','CC', ...
	'Style','checkbox', ...
	'Tag','PAOATraceCC', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOA', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[27 50 58 10], ...
	'String','Ch', ...
	'Style','checkbox', ...
	'Tag','PAOATraceCh', ...
   'Value',1);
%-------------------------------------PAOB-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_PAOB', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[70 140 50 10], ...
	'String','PAOB', ...
	'Style','checkbox', ...
	'Tag','CheckboxPAOB', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 125 50 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceCD', ...
   'Value',1);
% Calibration Eddy check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 110 50 10], ...
	'String','CE', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceCE', ...
   'Value',1);
% Calibration Profile check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 95 50 10], ...
	'String','CP', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceCP', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 80 50 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceEC', ...
   'Value',1);
% Calibration Chamber check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 65 50 10], ...
	'String','CC', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceCC', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOB', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[77 50 50 10], ...
	'String','Ch', ...
	'Style','checkbox', ...
	'Tag','PAOBTraceCh', ...
   'Value',1);
%-------------------------------------PAOJ-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','site_check_PAOJ', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[120 140 50 10], ...
	'String','PAOJ', ...
	'Style','checkbox', ...
	'Tag','CheckboxPAOJ', ...
   'Value',1);
% Climate/Diagnostics check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 125 50 10], ...
	'String','CD', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceCD', ...
   'Value',1);
% Calibration Eddy check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 110 50 10], ...
	'String','CE', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceCE', ...
   'Value',1);
% Calibration Profile check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 95 50 10], ...
	'String','CP', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceCP', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 80 50 10], ...
	'String','EC', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceEC', ...
   'Value',1);
% Calibration Chamber check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 65 50 10], ...
	'String','CC', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceCC', ...
   'Value',1);
% Eddy Correlation check button
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
   'BackgroundColor',[0.8 0.8 0.8], ...
   'Callback','select_PAOJ', ...
	'FontSize',10, ...
   'ListboxTop',0, ...
   'Max', 1, ...
   'Position',[127 50 50 10], ...
	'String','Ch', ...
	'Style','checkbox', ...
	'Tag','PAOJTraceCh', ...
   'Value',1);
%-------------------------------------Year:-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[160 157 37 16], ...
	'String','Year:', ...
	'Style','text', ...
   'Tag','StaticText2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[200 157 40 16], ...
	'String',mat3, ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
   'Value',length(mat3));
%-------------------------------------Last 7 days-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','view_sites_radio', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
   'Max',3, ...
   'Position',[172 138 100 16], ...
	'String','Last 7 days', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton1', ...
   'Value',3);
%-------------------------------------Last 14 days-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','view_sites_radio', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Max',3, ...
	'Position',[172 122 100 16], ...
	'String','Last 14 days', ...
	'Style','radiobutton', ...
   'Tag','Radiobutton2');
%-------------------------------------Last 30 days-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','view_sites_radio', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Max',3, ...
	'Position',[172 104 100 16], ...
	'String','Last 30 days', ...
	'Style','radiobutton', ...
	'Tag','Radiobutton3', ...
   'UserData','[ ]');
%-------------------------------------Select DOYs-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Callback','view_sites_radio', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Max',3, ...
	'Position',[172 86 100 16], ...
	'String','Select DOYs', ...
	'Style','radiobutton', ...
   'Tag','Radiobutton4');
%-------------------------------------from:-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[170 60 25 18], ...
	'String','from:', ...
	'Style','text', ...
	'Tag','StaticText3', ...
   'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',10, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[200 60 30 18], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','fromDOY', ...
   'Visible','off');
%-------------------------------------to:-------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[230 60 20 18], ...
	'String','to:', ...
	'Style','text', ...
	'Tag','StaticText4', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',10, ...
	'HorizontalAlignment','right', ...
	'ListboxTop',0, ...
	'Position',[255 60 30 18], ...
	'String','1', ...
	'Style','edit', ...
	'Tag','toDOY', ...
   'Visible','off');
%-------------------------------------Diagnostics Only Checkbox------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
   'Position',[20 18 100  16], ...    
	'String','Diagnostics only', ...
	'Style','checkbox', ...
	'Tag','CheckboxDiag', ...
   'Value',1);
%-------------------------------------File Status----------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','fileStatus;', ...
	'ListboxTop',0, ...
	'Position',[280 210 46 21], ...
	'String','File Status', ...
   'Tag','Pushbutton1');
%-------------------------------------Clear All----------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','clear_all', ...
	'ListboxTop',0, ...
	'Position',[120 15 46 21], ...
	'String','Clear All', ...
   'Tag','Pushbutton1');
%----------------------------View Selected Sights Button-------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','View_selected_sites(gcf);', ...
	'ListboxTop',0, ...
	'Position',[180 15 46 21], ...
	'String','View', ...
   'Tag','Pushbutton1');
%-------------------------------------Exit---------------------------------------
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','close all;', ...
	'ListboxTop',0, ...
	'Position',[240 15 46 21], ...
	'String','Exit', ...
   'Tag','Pushbutton1');
if nargout > 0, fig = h0; end
