function [co2,h2o,Tbench,Plicor,Pgauge] = fr_profile_licor_calc(RawData_mV,Profile)
switch upper(Profile.Licor.Type)
    case '6262'
        [co2,h2o,Tbench,Plicor]= fr_licor_calc(Profile.Licor.Num,Profile.Licor.CalDate, ...
                                RawData_mV(:,1),RawData_mV(:,2), ...
                                RawData_mV(:,3),RawData_mV(:,4),...
                                Profile.Licor.CO2_cal,Profile.Licor.H2O_cal);
        Pgauge = polyval(Profile.Pgauge.Poly,RawData_mV(:,5));
        Pgauge = filtfilt(Profile.Pgauge.filt_b,Profile.Pgauge.filt_a, Pgauge);

    case '6252'
        Pbarometric = 94; %!!! THIS SHOULD BE REPLACED BY MEASURED VALUE (IN SECOND STAGE CLEANING)!!!
        [co2,Tbench,Pgauge,Plicor] = fr_licor6252_calc(Profile.Licor.Num,Profile.Licor.CalDate, ...
                                     RawData_mV(:,1),RawData_mV(:,3),Pbarometric, ...
                                     RawData_mV(:,5),Profile.Pgauge.Poly, ...
                                     Profile.Licor.CO2_cal);
        h2o = [];
                                  
    case '800'
        co2 = fr_LI800_calc(RawData_mV,...
                            Profile.Licor.c_range,...
                            Profile.Licor.v_range,...
                            Profile.Licor.c_offset,...
                            Profile.Licor.CO2_cal);
        h2o = []; Tbench = []; Plicor = []; Pgauge = []; 
                         
    otherwise
        error 'Wrong IRGA type!'
        
end
