function [fitresult, gof] = createSurfaceFit(Ts_param, SM_param, R_param)
%CREATESURFACEFIT(TS_PARAM,SM_PARAM,R_PARAM)
%  Fit surface to data.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Ts_param
%      Y Input : SM_param
%      Z output: R_param
%      Weights : (none)
%
%  Output:
%      fitresult : an sfit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, SFIT.

%  Auto-generated by MATLAB on 25-Nov-2010 15:02:13


%% Fit: 'untitled fit 1'.
ft = fittype( '(a.*b.^( (x-10)./10)).*(1./(1 + exp(c -d.*y)) )', 'indep', {'x', 'y'}, 'depend', 'z' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf -Inf -Inf];
opts.StartPoint = [0.565334348366409 0.889524736884559 0.871291765763986 0.271620945475081];
opts.Upper = [Inf Inf Inf Inf];
opts.Weights = zeros(1,0);
[fitresult, gof] = fit( [Ts_param, SM_param], R_param, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [Ts_param, SM_param], R_param );
legend( h, 'untitled fit 1', 'R_param vs. Ts_param, SM_param', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Ts_param' );
ylabel( 'SM_param' );
zlabel( 'R_param' );
grid on
view( 81.5, 26 );


