function dataforRachelle_cr;
%Data for Rachelle from CR site
%

% kai* April 19, 2004 base on dataforal_cr
%
% Revisions:     

format short g;

[yyyy,mm, dd] = datevec(now);
years   = yyyy;

ptha  = biomet_path('yyyy','cr','Climate\clean');

GMT_shift = 8/24;       %shift grenich mean time to 24hr day
tv        = read_bor([ptha 'clean_tv'],8,[],years);
tv = tv-GMT_shift;

ind = find(tv<floor(now)-1);

traces_to_load = {...
      'air_temperature_hmp_40m',...
      'air_temperature_hmp_27m',...
      'air_temperature_hmp_4m',...
      'relative_humidity_hmp_40m',...
      'relative_humidity_hmp_27m',...
      'relative_humidity_hmp_4m',...
      'soil_temperature_5mm',...
      'soil_temperature_1cm',...
      'soil_temperature1_2cm',...
      'soil_temperature_5cm',...
      'soil_temperature_10cm',...
      'soil_temperature_20cm',...
      'soil_temperature_50cm',...
      'soil_temperature_100cm',...
      'soil_moisture_1cm_2cm',...
      'soil_moisture_10cm_12cm',...
      'soil_moisture_30cm_50cm',...
      'soil_moisture_70cm_100cm',...
      'precipitation_1',...
};
traces_units = {...
      '^oC',...
      '^oC',...
      '^oC',...
      '%',...
      '%',...
      '%',...
      '^oC',...
      '^oC',...
      '^oC',...
      '^oC',...
      '^oC',...
      '^oC',...
      '^oC',...
      '^oC',...
      'm^{3} m^{-3}',...
      'm^{3} m^{-3}',...
      'm^{3} m^{-3}',...
      'm^{3} m^{-3}',...
      'mm/30min',...
};

get_traces_db('cr',years,'climate',traces_to_load);

datevector = datevec(tv);

output = [datevector(:,1) ...
      datevector(:,2) ...
      datevector(:,3) ...
      datevector(:,4) ...
      datevector(:,5)];

string_mat  = 'Year,Month,Day,Hr,Min';
string_unit = ' , , , , ';
string_form = '%4i,%2i,%2i,%2i,%2i';

for i = 1:length(traces_to_load)
   eval(['output = [output ' char(traces_to_load(i)) '];']);   
   string_mat  = [string_mat,',',char(traces_to_load(i))];
   string_unit = [string_unit,',',char(traces_units(i))];
   string_form = [string_form,',%4.2f'];
end

fname = (['D:\Sites\web_page_weather\cr_rachelle.txt']);

FID = fopen(fname, 'wt');
fprintf(FID, '%s\n',string_mat);
fprintf(FID, '%s\n',string_unit);
fprintf(FID, [string_form '\n'],output(ind,:)');
fclose(FID);

return
