function [dataPth,hhourPth,databasePth,csi_netPth] = fr_get_local_path
ls = addpath_loadstart;

%This file is generated by fr_set_site.m
%Please do not edit - use fr_set_site instead!


%dataPth  = 'd:\met-data\data\';
%hhourPth  = 'd:\met-data\hhour\';
%databasePth  = '';
dataPth  = [ls 'SiteData/TP39/MET-DATA/data/'];
hhourPth  = [ls 'SiteData/TP39/MET-DATA/hhour/'];
databasePth  = [ls 'SiteData/TP39/MET-DATA/meteo/'];
csi_netPth = '[]';
