Stats_all = fcrn_load_data(datenum(2003,8,10:33),'NB');
 
% Primitive cleaning 
co2 = real(get_stats_field(Stats_all,'MainEddy.Three_Rotations.Avg(5)'));
h2o = real(get_stats_field(Stats_all,'MainEddy.Three_Rotations.Avg(6)'));
ind_exclude = find(T_std > 5 | co2<300 | co2>450);

% Variables to export

Var = [...
   {'MainEddy.Three_Rotations.Avg(1)'  ,'Wind_Speed_U_Avg','m s^{-1}'}',...
   {'MainEddy.Three_Rotations.Avg(4)'  ,'Air_Temperature_Avg','^oC'}',...
   {'MainEddy.Three_Rotations.Avg(5)'  ,'CO2_Mixing_Ratio_Avg','\mumol mol^{-1} dry air'}',...
   {'MainEddy.Three_Rotations.Avg(6)'  ,'H2O_Mixing_Ratio_Avg','mmol mol^{-1} dry air'}',...
   {'MiscVariables.BarometricP'        ,'Barometric_Pressure','kPa'}',...
   {'MainEddy.Three_Rotations.Std(1)'  ,'Wind_Speed_U_Std','m s^{-1}'}',...
   {'MainEddy.Three_Rotations.Std(2)'  ,'Wind_Speed_V_Std','m s^{-1}'}',...
   {'MainEddy.Three_Rotations.Std(3)'  ,'Wind_Speed_W_Std','m s^{-1}'}',...
   {'MainEddy.Three_Rotations.Std(4)'  ,'Air_Temperature_Std','^oC'}',...
   {'MainEddy.Three_Rotations.Std(5)'  ,'CO2_Mixing_Ratio_Std','\mumol mol^{-1} dry air'}',...
   {'MainEddy.Three_Rotations.Std(6)'  ,'H2O_Mixing_Ratio_Std','mmol mol^{-1} dry air'}',...
   {'MainEddy.Three_Rotations.AvgDtr.Fluxes.Hs'   ,'Sensible_Heat_Flux','W m^{-2}'}',...
   {'MainEddy.Three_Rotations.AvgDtr.Fluxes.LE_L' ,'Latent_Heat_Flux','W m^{-2}'}',...
   {'MainEddy.Three_Rotations.AvgDtr.Fluxes.Fc'   ,'CO2_Flux','\mumol m^{-2} s^{-1}'}',...
   {'MainEddy.Three_Rotations.AvgDtr.Fluxes.Ustar','Friction_Velocity','m s^{-1}'}',...
   {'MainEddy.Three_Rotations.AvgDtr.Fluxes.Hs'   ,'Sensible_Heat_Flux_Sonic','W m^{-2}'}'......
      ];

% Create trace structure for export function

tv = get_stats_field(Stats_all,'TimeVector') + 4/24 ;
rec_tv = get_stats_field(Stats_all,'RecalcTime');
Year = datevec(tv(3));
Year = Year(1);

for i = 1:length(Var)
   eval(['x = real(get_stats_field(Stats_all,''' char(Var(1,i)) '''));']);
   eval(['trc(i).SiteID = ''NB'';']);
   eval(['trc(i).Year = Year;']);
   eval(['trc(i).timeVector = tv;']);
   eval(['trc(i).data = x;']);
   eval(['trc(i).data(ind_exclude) = NaN;']);
   eval(['trc(i).ini.FCRN_Variable = ''' char(Var(2,i)) ''';']);
   eval(['trc(i).ini.FCRN_DataType = ''Flx_UBC'';']);
   eval(['trc(i).ini.units = ''' char(Var(3,i)) ''';']);
   eval(['trc(i).Last_Updated = datestr(max(rec_tv));']);
end   

fcrn_table_export(trc','Flx_UBC','c:\temp\')