function fcrn_export_xsite(Stats_all,flag)

% Variables to export
Var = [...
   {'Instrument(1).Avg(1)' ,'U_Avg','m s^{-1}'}',...
   {'Instrument(1).Std(1)' ,'U_Std','m s^{-1}'}',...
   {'Instrument(1).Avg(2)' ,'V_Avg','m s^{-1}'}',...
   {'Instrument(1).Std(2)' ,'V_Std','m s^{-1}'}',...
   {'Instrument(1).Avg(3)' ,'W_Avg','m s^{-1}'}',...
   {'Instrument(1).Std(3)' ,'W_Std','m s^{-1}'}',...
   {'Instrument(1).Avg(4)' ,'Tsonic_Avg','m s^{-1}'}',...
   {'Instrument(1).Std(4)' ,'Tsonic_Std','m s^{-1}'}',...
   {'Instrument(2).Avg(1)' ,'s_CO2_Avg_LI7000','\mumol mol^{-1} dry air'}',...
   {'Instrument(2).Std(1)' ,'s_CO2_Std_LI7000','\mumol mol^{-1} dry air'}',...
   {'Instrument(2).Avg(2)' ,'s_H2O_Avg_LI7000','mmol mol^{-1} dry air'}',...
   {'Instrument(2).Std(2)' ,'s_H2O_Avg_LI7000','mmol mol^{-1} dry air'}',...
   {'Instrument(3).Avg(1)' ,'rho_CO2_Avg_LI7000','\mumol m^{-3}'}',...
   {'Instrument(3).Std(1)' ,'rho_CO2_Std_LI7000','\mumol m^{-3}'}',...
   {'Instrument(3).Avg(2)' ,'rho_H2O_Avg_LI7000','mmol mol^{-3}'}',...
   {'Instrument(3).Std(2)' ,'rho_H2O_Avg_LI7000','mmol mol^{-3}'}',...
   {'Instrument(4).Avg(1)' ,'p_barometric_avg','kPa'}',...
   {'Instrument(5).Avg(1)' ,'T_air_avg_best_estimate','^oC'}',...
   {'XSITE_CP.Three_Rotations.AvgDtr.Fluxes.Ustar','Friction_Velocity','m s^{-1}'}',...
   {'XSITE_CP.Three_Rotations.AvgDtr.Fluxes.Hs'   ,'Hs_CP','W m^{-2}'}',......
   {'XSITE_CP.Three_Rotations.AvgDtr.Fluxes.LE_L' ,'LE_CP','W m^{-2}'}',...
   {'XSITE_CP.Three_Rotations.AvgDtr.Fluxes.Fc'   ,'F_CO2_CP','\mumol m^{-2} s^{-1}'}',...
   {'XSITE_OP.Three_Rotations.AvgDtr.Fluxes.Hs'   ,'Hs_OP','W m^{-2}'}',......
   {'XSITE_OP.Three_Rotations.AvgDtr.Fluxes.LE_L' ,'LE_OP','W m^{-2}'}',...
   {'XSITE_OP.Three_Rotations.AvgDtr.Fluxes.Fc'   ,'F_CO2_OP','\mumol m^{-2} s^{-1}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,1)' ,'cov_u_u_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,2)' ,'cov_u_v_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,3)' ,'cov_u_w_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,4)' ,'cov_u_Ta_CP','m s^{-1} ^oC'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,5)' ,'cov_u_CO2_CP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(1,6)' ,'cov_u_H2O_CP','m s^{-1} mmol mol^{-1} dry air'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(2,2)' ,'cov_v_v_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(2,3)' ,'cov_v_w_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(2,4)' ,'cov_v_Ta_CP','m s^{-1} ^oC'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(2,5)' ,'cov_v_CO2_CP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(2,6)' ,'cov_v_H2O_CP','m s^{-1} mmol mol^{-1} dry air'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(3,3)' ,'cov_w_w_CP','m^2 s^{-2}'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(3,4)' ,'cov_w_Ta_CP','m s^{-1} ^oC'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(3,5)' ,'cov_w_CO2_CP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_CP.Zero_Rotations.AvgDtr.Cov(3,6)' ,'cov_w_H2O_CP','m s^{-1} mmol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,1)' ,'cov_u_u_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,2)' ,'cov_u_v_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,3)' ,'cov_u_w_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,4)' ,'cov_u_Ta_OP','m s^{-1} ^oC'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,5)' ,'cov_u_CO2_OP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(1,6)' ,'cov_u_H2O_OP','m s^{-1} mmol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(2,2)' ,'cov_v_v_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(2,3)' ,'cov_v_w_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(2,4)' ,'cov_v_Ta_OP','m s^{-1} ^oC'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(2,5)' ,'cov_v_CO2_OP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(2,6)' ,'cov_v_H2O_OP','m s^{-1} mmol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(3,3)' ,'cov_w_w_OP','m^2 s^{-2}'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(3,4)' ,'cov_w_Ta_OP','m s^{-1} ^oC'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(3,5)' ,'cov_w_CO2_OP','m s^{-1} \mumol mol^{-1} dry air'}',...
   {'XSITE_OP.Zero_Rotations.AvgDtr.Cov(3,6)' ,'cov_w_H2O_OP','m s^{-1} mmol mol^{-1} dry air'}',...
];

% Create trace structure for export function

tv = get_stats_field(Stats_all,'TimeVector');
rec_tv = get_stats_field(Stats_all,'RecalcTime');
Year = datevec(tv(3));
Year = Year(1);

for i = 1:length(Var)
   eval(['x = real(get_stats_field(Stats_all,''' char(Var(1,i)) '''));']);
   eval(['trc(i).SiteID = ''XSITE'';']);
   eval(['trc(i).Year = Year;']);
   eval(['trc(i).timeVector = tv;']);
   eval(['trc(i).data = x;']);
%   eval(['trc(i).data(ind_exclude) = NaN;']);
   eval(['trc(i).ini.FCRN_Variable = ''' char(Var(2,i)) ''';']);
   eval(['trc(i).ini.FCRN_DataType = ''Flx_UBC'';']);
   eval(['trc(i).ini.units = ''' char(Var(3,i)) ''';']);
   eval(['trc(i).Last_Updated = datestr(max(rec_tv));']);
end   

fcrn_table_export(trc','Flx_UBC','e:\')