function Stats_all = fcrn_load_external(currentDate,SiteId,pth)
% Stats_all = fcrn_load_external(currentDate,SiteId)
%
% Assumes site setup has been run !!!!

%----------------------------------------------------
% Define variables to be extracted for the system
%----------------------------------------------------
% This list is just a copy of the one in fcrn_plot_report
variable_info = [...
      {'Three_Rotations.AvgDtr.Fluxes.Hs','Hs','W m^{-2}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.LE_L','LE','W m^{-2}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.Fc','Fc','\fontname{Symbol}m\fontname{Arial}mol m^{-2} s^{-1}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.Ustar','Ustar','m/s'}',...
   {'Three_Rotations.Avg(1)','U_Avg','m/s'}',...
      {'Three_Rotations.Std(1)','U_Std','m/s'}',...
      {'Three_Rotations.Std(2)','V_Std','m/s'}',...
      {'Three_Rotations.Std(3)','W_Std','m/s'}',...
   {'Three_Rotations.Std(4)','Ta_Std','^oC'}',...
      {'Three_Rotations.Avg(4)','Ta_Avg','^oC'}',...
      {'Three_Rotations.Angles.Eta','eta','deg'}',...
      {'Three_Rotations.Angles.Theta','theta','deg'}',...
   {'Three_Rotations.Avg(5)','CO2_Avg','ppm'}',...
      {'Three_Rotations.Std(5)','CO2_Std','ppm'}',...
   	{'Three_Rotations.Avg(6)','H2O_Avg','mmol m^{-2} s^{-1}'}',...
      {'Three_Rotations.Std(6)','H2O_Std','mmol m^{-2} s^{-1}'}',...
   ];
no_var = length(variable_info);

%--------------------------------------------------
% System specific part
%--------------------------------------------------
% fr_calc_main calculations
variable_external = [...
      {'stats.Fluxes.AvgDtr(:,2)'}',...
      {'stats.Fluxes.AvgDtr(:,1)'}',...
      {'stats.Fluxes.AvgDtr(:,5)'}',...
      {'stats.Fluxes.AvgDtr(:,9)'}',...
   {'squeeze(stats.AfterRot.AvgMinMax(1,14,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(4,14,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(4,16,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(4,12,:))'}',...
   {'squeeze(stats.AfterRot.AvgMinMax(4,13,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(1,13,:))'}',...
      {'stats.Angles(:,1)'}',...
      {'stats.Angles(:,2)'}',...
   {'squeeze(stats.AfterRot.AvgMinMax(1,6,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(4,6,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(1,7,:))'}',...
      {'squeeze(stats.AfterRot.AvgMinMax(4,7,:))'}',...
   ];


% [dd,pth] = fr_get_local_path;
c = fr_get_init(SiteId, currentDate(1));
system_names   = {'MainEddy_Old'};

for i = 1:length(system_names)
   Stats_all(1).Configuration.System(i).FieldName = char(system_names(i));
end
Stats_all(1).Configuration.Instrument = [];

for j = 1:no_var
   [tv,x] = fr_join_trace(char(variable_external(j)),currentDate(1),currentDate(end),c.hhour_ext,pth);
   eval([char(variable_info(2,j)) ' = x;']);
   for i = 1:length(x)
   	eval(['Stats_all(i).' char(system_names(1)) '.' char(variable_info(1,j)) ' = ' char(variable_info(2,j)) '(i);']);
   end
end

dv = datevec(currentDate(1));
for i = 1:length(x)
   Stats_all(i).TimeVector = tv(i) + datenum(dv(1),1,1);
end

return