function variable_info = flux_comp
% variable_info = report_var
%
% Generates fcrn_plot_comp setup:
% This is the list of variables that will be plotted, 
% four at a time in a four panel graph in the order 
% given in this function
% The three entries per variable are 
% the fieldName, the variableName and the variableUnit

disp('Using LinDtr and Var');

% Four plots per panel
variable_info = [...
     {'Three_Rotations.LinDtr.Fluxes.Hs','Hs','W m^{-2}'}',...
      {'Three_Rotations.LinDtr.Fluxes.LE_L','LE','W m^{-2}'}',...
      {'Three_Rotations.LinDtr.Fluxes.Fc','Fc','\fontname{Symbol}m\fontname{Arial}mol m^{-2} s^{-1}'}',...
      {'Three_Rotations.LinDtr.Fluxes.Ustar','Ustar','m/s'}',...
     {'Three_Rotations.Avg(1)','U_Avg','m/s'}',...
      {'Three_Rotations.LinDtr.Cov(1,1)','U_Var','m/s'}',...
      {'Three_Rotations.LinDtr.Cov(2,2)','V_Var','m/s'}',...
      {'Three_Rotations.LinDtr.Cov(3,3)','W_Var','m/s'}',...
   ];

% For plotting replace the underscore
variable_info(4,:) = strrep(variable_info(2,:),'_','\_');

