function variable_info = sonic_comp
% variable_info = report_std
%
% Generates fcrn_plot_comp setup:
% This is the list of variables that will be plotted, 
% four at a time in a four panel graph in the order 
% given in this function
% The three entries per variable are 
% the fieldName, the variableName and the variableUnit

disp('Sonic comparison using instrument data');

% Four plots per panel
disp('Using LinDtr and Var');
variable_info = [...
     {'Cov_Rotated(3,4)','wp_Tsp','W m^{-2}'}',...
      {'Cov_Rotated(1,1)','U_Var','m/s'}',...
      {'Cov_Rotated(3,3)','W_Var','m/s'}',...
      {'Cov_Rotated(4,4)','Ta_Var','^oC'}',...
     {'Avg_Rotated(1)','U_Avg','m/s'}',...
      {'MiscVariables.WindDirection','dir','deg'}',...
      {'Cov_Rotated(2,2)','V_Var','m/s'}',...
      {'Avg(4)','Ta_Avg','^oC'}',...
   ];

% For plotting replace the underscore
variable_info(4,:) = strrep(variable_info(2,:),'_','\_');

