function variable_info = report_var
% variable_info = report_var
%
% Generates fcrn_plot_comp setup:
% This is the list of variables that will be plotted, 
% four at a time in a four panel graph in the order 
% given in this function
% The three entries per variable are 
% the fieldName, the variableName and the variableUnit

disp('Using AvgDtr and Std');

% Four plots per panel
variable_info = [...
     {'Three_Rotations.AvgDtr.Fluxes.Hs','Hs','W m^{-2}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.LE_L','LE','W m^{-2}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.Fc','Fc','\fontname{Symbol}m\fontname{Arial}mol m^{-2} s^{-1}'}',...
      {'Three_Rotations.AvgDtr.Fluxes.Ustar','Ustar','m/s'}',...
     {'Three_Rotations.Avg(1)','U_Avg','m/s'}',...
      {'Three_Rotations.Std(1)','U_Std','m/s'}',...
      {'Three_Rotations.Std(2)','V_Std','m/s'}',...
      {'Three_Rotations.Std(3)','W_Std','m/s'}',...
     {'Three_Rotations.Angles.Eta','eta','deg'}',...
      {'Three_Rotations.Std(3)','w_Avg','m/s'}',...
      {'Three_Rotations.Std(4)','Ta_Std','^oC'}',...
      {'Three_Rotations.Avg(4)','Ta_Avg','^oC'}',...
     {'Three_Rotations.Avg(5)','CO2_Avg','ppm'}',...
      {'Three_Rotations.Std(5)','CO2_Std','ppm'}',...
   	  {'Three_Rotations.Avg(6)','H2O_Avg','mmol m^{-2} s^{-1}'}',...
      {'Three_Rotations.Std(6)','H2O_Std','mmol m^{-2} s^{-1}'}',...
   ];

% For plotting replace the underscore
variable_info(4,:) = strrep(variable_info(2,:),'_','\_');

