function variable_info = sonic_cal
% variable_info = report_std
%
% Generates fcrn_plot_comp setup:
% This is the list of variables that will be plotted, 
% four at a time in a four panel graph in the order 
% given in this function
% The three entries per variable are 
% the fieldName, the variableName and the variableUnit

disp('get a backup of the function sonic_comp');
disp('Sonic comparison using variances');

% Four plots per panel
disp('Using LinDtr and Var');
variable_info = [...
     {'Three_Rotations.AvgDtr.Fluxes.Hs','Hs','W m^{-2}'}',...
      {'Three_Rotations.AvgDtr.Std(1)','U_Var','m/s'}',...
      {'Three_Rotations.AvgDtr.Std(3)','W_Var','m/s'}',...
      {'Three_Rotations.AvgDtr.Std(4)','Ta_Var','^oC'}',...
     {'Three_Rotations.Avg(1)','U_Avg','m/s'}',...
      {'Zero_Rotations.Avg(3)','w_Avg','m/s'}',...
      {'Three_Rotations.AvgDtr.Std(2)','V_Var','m/s'}',...
      {'Three_Rotations.Avg(4)','Ta_Avg','^oC'}',...
   ];

% For plotting replace the underscore
variable_info(4,:) = strrep(variable_info(2,:),'_','\_');

