function traces_out = berms_highlevel_structure(traces)
% traces = berms_highlevel_structure(traces)
%
% Takes requested traces from structure and copies them to the output structure
% and renames them.
%
%	kai* 	Created:			22 Dec, 2000
%			Last Modified: 13 Sept, 2001

out_names = {...
   'Net_Rad_AbvCnpy_31m',...
   'Sensible_HeatFlux_AbvCnpy_39m',...
   'Latent_HeatFlux_AbvCnpy_39m',...
   'Soil_HeatFlux_0cm',...
	'Biomass_HeatStorage_0to21m',...
	'SensisbleAir_HeatStorage_0to39m',...
	'LatentAir_HeatStorage_0to39m',...
	'Total_HeatStorage_0to39m',...
	'CarbonDioxide_Flux_39m',...
	'NetEcosystemExchange',...
	'FrictionVelocity_39m',...
   'CarbonDioxide_Concentration_39m'};

in_names = {...
   'radiation_net_main',...
   'h_main',...
   'le_main',...
   'energy_storage_soil',...
	'energy_storage_biomass',...
	'energy_storage_sensible_heat',...
	'energy_storage_latent_heat',...
	'energy_storage_total',...
	'fc_main',...
	'nee_main',...
	'ustar_main',...
   'co2_avg_main'};

[dummy,ind_in,ind_trc] = intersect(in_names,{traces(:).variableName});
[dum,ind_s] = sort(ind_in);
ind_trc = ind_trc(ind_s);

for i = 1:length(ind_trc)
   traces_out(i) = traces(ind_trc(i));
   traces_out(i).variableName = char(out_names(i));
end

