function data_out = setup_menu_screen(action,top)
%This function is a small setup menu used with the 'main_traces_load' menu screen.
%This setup menu allows users to select the input path of uncleaned traces
%to work on, and the location and data format of traces being exported.

switch action
case 'init' 
   color_bg = [0.85 0.85 0.85];
   offset = 0;
   font_offset = 0;
   rec_pos = get(0,'screensize');
   if rec_pos(4)>=768      
      offset = 150;
      font_offset = 2;
   end
   
   lc_path = top.lc_path;
   out_path = top.lc_path;
   Year = top.trace_str(1).Year;
   NumDays =  datenum(Year+1,1,1) - datenum(Year,1,1) + 1;
   daystart = '1';
   dayend   = num2str(NumDays);   
   
   if ~isempty(top.set_up)
      if ~strcmp(lower(top.set_up.in_path),'database')
         lc_path = top.set_up.in_path;         
      end
      if ~strcmp(lower(top.set_up.out_path),'database')
         out_path = top.set_up.out_path;         
      end 
      if ~isempty(top.set_up.days)
         daystart = num2str(top.set_up.days(1));
         dayend = num2str(top.set_up.days(2));
      end      
   end    
   str1 = ['[Biomet Group Database]|' lc_path];
   str2 = [out_path '|[Biomet Group Database]'];
   
   fig_num =dialog('handlevisibility','on','IntegerHandle','off',...
      'NumberTitle','off','MenuBar','none','color',color_bg,...
      'position',[120 60 600+offset*1.5 270+offset*0.4],'Tag','setup menu');
   
   h = uicontrol(fig_num,...
      'style','text','units','pixels',...
      'position',[150 150 200 25],...
      'string','TEST',...
      'fontunits','pixels','FontSize',12);   
   hght = get(h,'extent');
   delete(h);
   
   if hght(4) < 20
      button_font = 12 + font_offset;
   else
      button_font = 8 + font_offset;
   end      
   
   
   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.01 .90 0.5 .08],...
      'string','Setup:','backgroundcolor',color_bg,'FontWeight','bold',...
      'fontsize',button_font,'HorizontalAlignment','left'); 

   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.03 .75 0.3 .08],...
      'string','Input Path:','HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   h_path_in = uicontrol(fig_num,...
      'style','popup',...
      'units','normalized','position',[0.18 .76 0.65 .08],...
      'string',str1,'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',[1 1 1]);
   h = uicontrol(fig_num,...
      'style','push','callback','setup_menu_screen(''browse_in'')',...
      'units','normalized','position',[0.84 .76 0.15 .08],'string','Browse',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   
   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.03 .61 0.3 .08],...
      'string','Output Path:	','HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg); 
   
   h_path_out = uicontrol(fig_num,...
      'style','popup',...
      'units','normalized','position',[0.18 .62 0.65 .08],...
      'string',str2,'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',[1 1 1]);
   h = uicontrol(fig_num,...
      'style','push','callback','setup_menu_screen(''browse_out'')',...
      'units','normalized','position',[0.84 .62 0.15 .08],...
      'string','Browse','HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   
   h = uicontrol(fig_num,...      
      'style','text',...
      'units','normalized','position',[0.03 .47 0.3 .08],...
      'string','Format: ','HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   
   h_form = uicontrol(fig_num,...
      'style','popup',...
      'units','normalized','position',[0.18 .48 0.65 .08],...
      'string',['Binary Cleaned   (Database Format)|Binary Raw   (Database Format)|Text (.txt)|Matlab Structure(.mat)|Matlab Data Column(.mat)'],...
      'fontsize',button_font,'backgroundcolor',[1 1 1]); 
   
   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.03 .28 0.5 .08],...
      'string','Day Of Year: ',...
      'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.28 .28 0.5 .08],...
      'string','Start Day:',...
      'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   h = uicontrol(fig_num,...
      'style','text',...
      'units','normalized','position',[0.58 .28 0.5 .08],...
      'string','End Day:',...
      'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',color_bg);
   h_str = uicontrol(fig_num,...
      'style','edit', 'units','normalized','position',[0.4+ offset*0.0002 .3-offset*0.0001 0.1 .08 + offset*0.0001],...
      'string',daystart,'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',[1 1 1]);
   h_end= uicontrol(fig_num,...
      'style','edit','units','normalized','position',[0.7+ offset*0.0002 .3-offset*0.0001  0.1 .08 + offset*0.0001],...
      'string',dayend,'HorizontalAlignment','left',...
      'fontsize',button_font,'backgroundcolor',[1 1 1]);
   
   h_cancel = uicontrol(fig_num,'style','push','HorizontalAlignment','left',...
      'units','normalized','position',[0.01 .03 0.2 .1],...
      'fontsize',button_font,...
      'string','Cancel','callback','set(gcf,''Tag'',''cancel'');');
   h_done = uicontrol(fig_num,'style','push','HorizontalAlignment','left',...
      'units','normalized','position',[0.79 .03 0.2 .1],...
      'fontsize',button_font,...
      'string','Done','callback','set(gcf,''Tag'',''done'');');
      
   set_up.in_path = lc_path;
   set_up.out_path = out_path;
  
   set_up.set_hndl = [h_path_in h_path_out h_form h_str h_end];
   
   set(gcf,'CloseRequestFcn','set(gcf,''Tag'',''cancel'');',...
      'UserData',set_up,'handlevisibility','callback');
   waitfor(fig_num,'Tag');
   set_up = get(fig_num,'UserData');
   data_out = '';
   if strcmp(get(fig_num,'Tag'),'done')
      s = ['bnc'; 'bnr'; 'txt'; 'mat'; 'mtc'];
      data_out.format = s(get(h_form,'Value'),:);
      data_out.in_path = 'database';
      data_out.out_path ='database';
      data_out.days = [1 NumDays];
      if get(h_path_in,'Value') == 2
         data_out.in_path = set_up.in_path;
      end
      if get(h_path_out,'Value')==1
         data_out.out_path = set_up.out_path;
      else
         warndlg('Setup: Saving Cleaned Traces into the Database!','WARNING!');
      end      
      strt_doy = str2num(get(h_str,'String'));
      end_doy = str2num(get(h_end,'String'));
      if ~isempty(strt_doy & end_doy) & (strt_doy <= end_doy)
         if strt_doy >=1 & end_doy <=NumDays
            data_out.days = [strt_doy  end_doy];
         end
      end      
   end   
   delete(fig_num);
case 'browse_in'
   set_up=get(gcf,'UserData');
   [fn pn] = uiputfile([set_up.in_path 'PATH'],'Choose Directory Path:');
   if pn~=0
      set_up.in_path = pn;
   else
      return
   end
   set(set_up.set_hndl(1),'String',['[Biomet Group Database]|' pn],'Value',2);
   set(gcf,'UserData',set_up);

case 'browse_out' 
   set_up=get(gcf,'UserData');
   [fn pn] = uiputfile([set_up.out_path 'PATH'],'Choose Directory Path:');
   if pn~=0
      set_up.out_path = pn;
   else
      return
   end
   set(set_up.set_hndl(2),'String',[pn '|[Biomet Group Database]'],'Value',1);
   set(gcf,'UserData',set_up);
case 'help'
   
end
