function data_out = ta_axis_options(action,top_fig)
%This is the setup menu for the axes options: grid and axis dimensions.
%
%	INPUT:  	'action' 	-species which case for each callback.
%				'top_fig'	-the figure handle of the top main interface.
%	OUTPUT:
%				'data_out'	-the structure containing the axes changes
%
switch action
case 'init'
   rec_pos = get(0,'screensize');
   offset = 0; 
   font_offset = 0;
   if rec_pos(4)==768
      offset = 150;
      font_offset = 2;
   end
   
	ylimits = NaN*ones(4,2);
   h_diag = dialog('handlevisibility','callback','IntegerHandle','off',...
      'NumberTitle','off','MenuBar','none',...
      'Name','Change Axis Settings','position',[100 100 475+offset 375+offset],...
      'Tag','change axis');
   
   %Test the font size:
   h = uicontrol(h_diag,...
      'style','text','units','pixels',...
      'position',[150 150 200 25],...
      'string','TEST',...
      'fontunits','pixels','FontSize',12);   
   hght = get(h,'extent');
   delete(h);
   
   if hght(4) < 20
      button_font = 12 + font_offset;
   else
      button_font = 8 + font_offset;
   end   
   
   h_t = uicontrol(h_diag,'style','text',...
      'Units','normalized','position',[0.05 0.9 0.3 0.05],...
      'string','	Axis ','fontsize',button_font,'HorizontalAlignment','left');
   %col = get(h_t,'BackgroundColor');
   %set(h,'color',col);
   h_t = uicontrol(h_diag,'style','text',...
      'Units','normalized','position',[0.25 0.9 0.3 0.05],...
      'string','	Ymin ','fontsize',button_font,'HorizontalAlignment','left');
   h_t = uicontrol(h_diag,'style','text',...
      'Units','normalized','position',[0.5 0.9 0.3 0.05],...
      'string','	Ymax ','fontsize',button_font,'HorizontalAlignment','left');
   
 
   ylimits(1,:) = get(top_fig.first_axis,'ylim');
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.05 0.8 0.2 0.05],...
      'string','Bottom Left:','fontsize',button_font,'HorizontalAlignment','right');
   h_ch1 =uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.75 0.8 0.2 0.05],...
      'string','Change','fontsize',button_font,'callback','ta_axis_options(''axis1'',1)');
   h_ymin(1) =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.3 0.8 0.2 0.05],...
      'string',num2str(ylimits(1,1)),'fontsize',button_font);
   h_ymax(1) =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.55 0.8 0.2 0.05],...
      'string',num2str(ylimits(1,2)),'fontsize',button_font);
   
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.05 0.7 0.2 0.05],...
      'string','Bottom Right:','fontsize',button_font,'HorizontalAlignment','right');
   h_ch2 =uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.75 0.7 0.2 0.05],...
      'string','Change','fontsize',button_font,'callback','ta_axis_options(''axis1'',2)',...
      'Enable','off');
   h_ymin(2) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.3 0.7 0.2 0.05],...
      'string','none','fontsize',button_font);
   h_ymax(2) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.55 0.7 0.2 0.05],...
      'string','none','fontsize',button_font);
   if ~isempty(top_fig.curr_ax_hdl)
      ylimits(2,:) = get(top_fig.curr_ax_hdl,'ylim');
      set(h_ch2,'Enable','on');
      set(h_ymin(2),'String',num2str(ylimits(2,1)));
      set(h_ymax(2),'String',num2str(ylimits(2,2)));
   end
   
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.05 0.6 0.2 0.05],...
      'string','Top Left:','fontsize',button_font,'HorizontalAlignment','right');
   h_ch3 =uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.75 0.6 0.2 0.05],...
      'string','Change','fontsize',button_font,'callback','ta_axis_options(''axis1'',3)',...
      'Enable','off');     
   h_ymin(3) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.3 0.6 0.2 0.05],...
      'string','none','fontsize',button_font);
   h_ymax(3) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.55 0.6 0.2 0.05],...
      'string','none','fontsize',button_font);
   if ~isempty(top_fig.other_ax_hdl)
      ylimits(3,:) = get(top_fig.other_ax_hdl,'ylim');
      set(h_ch3,'Enable','on');
      set(h_ymin(3),'String',num2str(ylimits(3,1)));
      set(h_ymax(3),'String',num2str(ylimits(3,2)));
   end
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.05 0.5 0.2 0.05],...
      'string','Top Right:','fontsize',button_font,'HorizontalAlignment','right');
   h_ch4 =uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.75 0.5 0.2 0.05],...
      'string','Change','fontsize',button_font,'callback','ta_axis_options(''axis1'',4)',...
      'Enable','off');   
   h_ymin(4) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.3 0.5 0.2 0.05],...
      'string','none','fontsize',button_font);
   h_ymax(4) = uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.55 0.5 0.2 0.05],...
      'string','none','fontsize',button_font);
   if ~isempty(top_fig.other_ax_hdl_right)
      ylimits(4,:) = get(top_fig.other_ax_hdl_right,'ylim');
      set(h_ch4,'Enable','on');
      set(h_ymin(4),'String',num2str(ylimits(4,1)));
      set(h_ymax(4),'String',num2str(ylimits(4,2)));
   end
   
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.23 0.35 0.5 0.05],...
      'string','Input range on the x-axis: ','fontsize',button_font,...
      'HorizontalAlignment','right');
   h_day = uicontrol(h_diag,'style','edit',...
      'Units','normalized','position',[0.75 0.36 0.2 0.055],...
      'string',num2str(top_fig.span),'fontsize',button_font,...
      'backgroundcolor',[1 1 1],'HorizontalAlignment','left');
   
   h_t =uicontrol(h_diag,'style','Text',...
      'Units','normalized','position',[0.23 0.23 0.5 0.05],...
      'string','Turn Grid On: ','fontsize',button_font,...
      'HorizontalAlignment','right');
   h_grid = uicontrol(h_diag,'style','popup',...
      'Units','normalized','position',[0.75 0.25 0.2 0.05],...
      'fontsize',button_font,'String','No|Yes','backgroundcolor',[1 1 1]);
   
   h_cancel = uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.05 0.05 0.2 0.05],...
      'string','Cancel','fontsize',button_font,...
      'callback','set(gcf,''Tag'',''cancel'')');
   h_done = uicontrol(h_diag,'style','push',...
      'Units','normalized','position',[0.75 0.05 0.2 0.05],...
      'string','Done','fontsize',button_font,...
      'callback','set(gcf,''Tag'',''done'')');
   
   ax_dat.h_ymin = h_ymin;		%set all necessary flags
   ax_dat.h_ymax = h_ymax;
   ax_dat.h_day = h_day;
   ax_dat.ylimits = ylimits;
   ax_dat.h_grid = h_grid;
   set(h_diag,'UserData',ax_dat);
   set(h_diag,'CloseRequestFcn','set(gcf,''Tag'',''cancel'')');
   
   %wait for the figure tag to change before quiting(close button or done button resets
   %the tag):
   waitfor(h_diag,'Tag');	
   data_out='';
   if strcmp(get(h_diag,'Tag'),'done')		%if tag set to done then get all info set
      val=get(h_grid,'Value');
      data_out.grid = 'off';
      if val==2
         data_out.grid = 'on';
      end        
      ax_dat = get(h_diag,'UserData');
      span = str2num(get(h_day,'String'));
      data_out.span  = span;
      data_out.ylimits = ax_dat.ylimits;
   end
   delete(h_diag);			%delete menu screen
case 'axis1'
   %this is the popup dialog box for user input
   %the values are stored into the user data for the axis menu screen.
   ind = top_fig;
   ax_dat = get(findobj('Tag','change axis'),'UserData');
   prompt={'Enter the minimum Y value:','Enter the maximum Y value:'};
   def={num2str(ax_dat.ylimits(ind,1)),num2str(ax_dat.ylimits(ind,2))};
   header='Input Axis Options';
   answer=inputdlg(prompt,header,1,def);
   if ~isempty(answer)
      s = cell2struct(answer',{'ymin','ymax'},2);
      if ~isempty(s.ymin) & ~isempty(s.ymax)
         ymin = str2num(s.ymin);
         ymax = str2num(s.ymax);         
         if ~isempty(ymin) & ~isempty(ymax)
            ax_dat.ylimits(ind,1) = ymin;
            ax_dat.ylimits(ind,2) = ymax;
            set(ax_dat.h_ymin(ind),'String',num2str(ymin));
            set(ax_dat.h_ymax(ind),'String',num2str(ymax));
            set(findobj('Tag','change axis'),'UserData',ax_dat);
         end         
      end    
   end
end
