function ta_help_menu(action)
if ~exist('action')
   action ='init';
end

switch action
case 'init'
 
%controls:
hlp_controls ={'The following are basic descriptions of the buttons available:',...
'',...
'',...      
'Previous Trace:',...
'	The ''Prev Trace'' button is used when working on muliple traces listed',...
'			in the initialization file.  When this button is pressed the previous',...
'			trace, from those chosen at the main menu, is loaded.',...
'	If the current working trace contains selected points, a warning message',...
'			is displayed.  If the current working trace is the first trace, then',...
'			another warning message is displayed.',...
'',...
'Next Trace:',...
'	The ''Next Trace'' button is used when working on muliple traces listed',...
'			in the initialization file.  When this button is pressed the next',...
'			trace, from those chosen at the main menu, is loaded.',...
'	If the current working trace contains selected points, a warning message',...
'			is displayed.  If the current working trace is the first trace, then',...
'			another warning message is displayed.',...
'',...
'scroll right:',...
'	The ''>'' button is used to scroll the x-axis by measured intervals in',...
'			 the right direction.  This interval is set in the Options/Axis menu.',...
'',...      
'scroll left:',...
'	The ''<'' button is used to scroll the x-axis by measured intervals in',...
'			 the left direction.  This interval is set in the Options/Axis menu.',...
'',...
'end right:',...
'	The ''>>'' button is used to shift the x-axis to the last interval of data',...
'			 available.  The interval range is set in the Options/Axis menu.',...
'',...
'end left:',...
'	The ''>>'' button is used to scroll the x-axis by measured intervals to',...
'			 the right.  The interval range is set in the Options/Axis menu.',...
''};

%context menu
hlp_context = {'The following is a description of the context menu (right mouse click):',...
'',...
'',...
'Remove Selected Points:',...
'	This option removes any selected points visible in the current plot window.',...
'			Any points selected outside this window are not affected.',...
'			For any points that are removed, linear interpolation is automatically',...
'			performed on the data in the current window.  By default, linear',...
'			interpolation will only be applied to single missing points.  The',...
'			maximum interpolation length can be changed in the Advanced Menu.',...
'',...
'Restore Selected Points',...
'	This option restores any selected points visible in the current plot window.',...
'			Any points selected outside this window are not affected.',...
'			For any points that are restored, linear interpolation is automatically',...
'			performed on the data in the current window.  By default, linear',...
'			interpolation will only be applied to single missing points.  The',...
'			maximum interpolation length can be changed in the Advanced Menu.',...
'',...
'Undo Last Operation'  ,...
'	The undo operation provides a way to convert back to the state previous to the',...
'			last operation.  The type of operations affected are removing and restoring',...
'			points using the right mouse click menu.  Also, the undo option will behave',...
'			the same way on any traces that are ''dependent'' on the current trace.',...
'			For more information on ''dependent'' traces, see the example initialization',...
'			file and the documentation.',...
'',...
'Redo Last Operation',...
'	The redo operation provides a way to convert back to the state previous to the',...
'			last undo command.  Also, the redo option will behave have the same effect',...
'			on any traces that are ''dependent'' on the current trace.',...
'			For more information on ''dependent'' traces, see the example initialization',...
'			and the documentation.',...
'',...
'UnSelect All Points'  ,...
'	This option removes all currently selected points in the entire trace.',...
'',...
'UnSelect Last Point',...
'	This option removes the last selected point in the entire trace, and is identical',...
'			to re-selecting the same point.',...
'',...
'Look at Fullview',...
'	The fullview command can be turned on and off with the shortcut key: "f"',...
'	This option changes the x-axis dimensions so that the entire trace is visible.',...
'',...
% kai* June 27, 2001
% Inserted a new menu point - very basic for now
'Look at HF Data',...
'	Loads the high frequency data from the current data directory',...
% end kai*
'',...   
'Turning Zoom On and Off',...
'	The zoom command can be turned on and off with the shortcut key: "z"',...
'	This option turns on a zoom command that is very similar to the matlab zoom',...
'			function.  In addition, this command will match zooming commands in the',...
'			working trace window, to any other imported traces in other axes.',...
'			All x-axes will be matched exactly, and the y-axes will be scaled to',...
'			match the scale change in the working y-axis.',...
'	To turn off the zoom command, the mouse must be right clicked outside the',...
'			working axis, but within the figure window.  This will activate the',...
'			context menu from the zoom command can be turned off.',...
'',...
'Number Points Selected',...
'	This is just a indicator of how many points are currently selected.',...
''};

%menu bar:
%File menu
hlp_file={'The following is a description of the File Menu:',...
'',...
'Save Trace Information: shortcut key is "s"',...
'	This option allows the user to save all the current cleaning information into a',...
'			matlab workspace file.  These files can be loaded later, in combination ',...
'			with the initialization file, to produce to current cleaned traces.',...
'',...
'Quit Program',...
'	This option will quit the cleaning program and prompt the user to save all',...
'			the current cleaning information.',...
''};
%Trace menu:
hlp_trace={'The following is a description of the Trace Menu:',...
'',...
'Importing Traces',...
'	This option allows other traces listed in the initialization file to be',...
'			imported for viewing.  If any imported traces are depenedent on the',...
'			working trace, points removed or restored will appear to affect these',...
'			traces as well. If removing or restoring points in multiple traces',...
'			is invoked from the Advanced Menu, all the corresponding imported traces',...
'			will also be updated.  The undo and redo command will also affect',...
'			any dependent, imported traces.',...
'',...
'	Import to Bottom Plot',...
'			The bottom plot is the first plot that is loaded onto the figure.',...
'			It contains the working trace located on the left axis.  It is possible',...
'			to import traces to the same axis as the working trace, or traces can',...
' 			be imported to the same plot, but with a different y-axis located on ',...
'			the right.',...
'',...
'	Import to Top Plot',...
'			When traces are imported to the top, the figure is spit into two',...
'			seperate plots.  The bottom plot contains the working trace on the',...
'			left axis, and any imported traces.  The top plot can also have two',...
'			seperate axes, one on the left and one on the right.  Each of these',...
'			left and right axis can have multiple traces present.',...
'',...
'	Removing Imported Traces',...
'			This option allows the removal of traces from any of the four axis that may',...
'			be present.  If the same trace has been imported in multiple locations',...
'			the order listed in the selection dialog box is: bottom right, bottom left,',...
'			top left, top right.  Removing traces from any axis will not affect dependent',...
'			traces; they will still be dependent on the current working trace.',...
''};

%Option menu
hlp_options = {'The following is a description of the Options Menu:',...
'',...
'Selection Type: Exact or X-axis',...
'			This option changes the procedure for selecting single points on the working.',...
'			trace.  The default is set to ''Exact'', which uses exact point picking.',...      
'			Points can only be selected when the cursor click falls directly over the',...
'			desired data.  When this option is set to ''X-axis'', points may be selected ',...
'			by clicking any position on the plot.  The x-coordinate of this position ',...
'			is used to select the closest data point along the x-axis.',...
'',...
'Trace Properties',...
'			This option creates a settings menu for the all the currently plotted traces.',...
'			From this menu the line color, line width, marker type, and marker size',...
'			can be changed.',...
'',...
'Axis Properties',...
'			This option creates a settings menu for the axes dimensions.  From this',...
'			menu the minimum and maximum values of each of the four possible y-axis can ',...
'			be changed.  Also, the the x-axis range can be changed, which will effect',...
'			all x-axes present.  It is also possible to set the grid on or off for all',...
'			the currently plotted axes, but this will not effect further imported traces.',...
'			Also, if muliple y-axes are being used (two possible on each plot), then',...
'			removing traces may cause the grid to disappear.',...
'',...
'View Legend',...
'			This option creates an independent figure listing all traces currently',...
'			plotted.  For each of these traces the color of line or marker is displayed.',...
'			If any of these traces is removed, or the color changed, the legend is',...
'			automatically updated.'};


%Advanced Menu
hlp_advanced={'The following is a description of the Advanced Menu:',...
	' ',...
'Filter Envelopes',...
'		Filter envelopes are created using a running mean and standard deviation',...
'			over the data set.',...
'		These filters are computed using input suplied by the user and remain',...
'			active while working on the current trace.  When quiting the session, or',...
'			loading the next or previous trace, these filters will be deleted.',...
'		To make these filters permanent, add the runningFilter field the ',...
'			initialization file.',...
'		Options for Filter envelopes are:',...
'			View Current:  This will display all filters created.',...
'			Create New:		This will allow the creation of new filters.',...
'			Remove Last:	This will remove the last created trace.',...
'',...
'Linear Interpolation',...   
'		Important: changing the max interpolation length can affect previous',...
'			calculations that used a higher interpolation length.',...
'		When restoring or removing points, the current interpolation length ',...
'			will effect every point within the current window AND within any',...
'			selected points within that window.',...
'		The max interpolation length also effects dependent traces and traces',...
'			selected with "remove/restore multiple traces" in the Advanced menu.',...
'',...
'Remove Points in Multiple Traces',...
'		This option allows removing points in multiple traces from those points',...
'			currently selected in the visible window.  Interpolation will also be',...
'			performed on each selected trace, using the current interpolation length.',...
'',...
'',...
'	Restore Points in Multiple Traces'...
'',...
'',...
'',...
'',...
'',...
'',...
'',...
'',...
'',...
'',...   
};
hlp_stats={'The following is a description of the Statistics Menu:',...
'',...
'	View Stats of Selected Points',...
'			This option shows the most recent cleaning operation performed on',...
'			selected points.  For each type of cleaning operation either the number',...
'			of points currently selected is shown, or the DOY index if only one point',...
'			is selected for that cleaning procedure.',...
'',...
'	View All Cleaning Results',...
'			This option shows all the current cleaning statistics for the working trace.',...
'			As the trace is updated, all the cleaning statistics will change too.',...
'			Note that only the most recent operation is shown for each point.',...
};


str={ 'File Menu' hlp_file;...
      'Trace Menu' hlp_trace;...
      'Options Menu' hlp_options;...
      'Advanced Menu' hlp_advanced;...
      'Context Menu' hlp_context;...
      'Buttons' hlp_controls;...
   	'Statistics' hlp_stats};
helpwin(str,'File Menu','Help')

end
