function ta_statsmenu(action)

top = get(gca,'UserData');
top.re_plot = 0;
top.new_axis = 0;

switch action
case 'stats'
   
   rec_pos = get(0,'screensize');	%check screen resolution and set offset if necessary
   offset = 0;   
   if rec_pos(4)>=766
      offset = 150;    
   end  
   
   hght = 0.05;
   pos = [450 100 350 + offset 400 + offset];
   if strcmp(top.local_use,'yes')
      hght = 0.1;
      pos = [450 100 300 200];
   end       
   if ~isempty(top.h_statbox)
      pos = get(top.h_statbox, 'Position');
      delete(top.h_statbox);
   end     
   
   h_statbox = figure('handlevisibility','off','IntegerHandle','off',...
      'NumberTitle','off','MenuBar','none','color',[0 0 0],...
      'Position',pos,'Name','Current Cleaning Stats');  
   if strcmp(top.local_use,'no')
      str = num2str(length(top.trace_var.pts_removed)...
         + length(top.trace_var.stats.clean_flags) ...
         + top.trace_var.stats.numpts.dependCleaned);            
      
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.91 0.90 hght],...
         'string','Total number of points cleaned: ',...
         'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.91 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   end
   if ~isempty(top.trace_var.interpolated)
      temp = length(find(~isnan(top.trace_var.interpolated) & ...
         top.trace_var.interpolated ~=0));
   else
      temp = 0;
   end   
   if strcmp(top.local_use,'no')
      temp = temp  + top.trace_var.stats.numpts.Interpolated;
   end
   
   str = num2str(temp);
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.05  0.83 0.90 hght],...
      'string','Total number of points interpolated: ',...
      'fontsize',9, 'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.85 0.83 0.10 hght],...
      'string',str,'fontsize',9, 'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   
   %check for 
   if ~isempty(top.trace_var.stats.index.PtsPastCurrentDate)
      currDayInd = min(top.trace_var.stats.index.PtsPastCurrentDate);
      tempNansCurr = top.trace_var.data(1:currDayInd-1);
   else
      tempNansCurr = top.trace_var.data;
   end
   
   str = num2str(length(find(isnan(tempNansCurr))));   
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.05 0.75 0.90 hght],...
      'string','Total number of NaNs: ',...
      'fontsize',9,'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.85 0.75 0.10 hght],...
      'string',str,'fontsize',9, 'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   
   str = num2str(length(top.trace_var.pts_removed));   
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.05 0.670 0.90 hght],...
      'string','Number of points manually removed: ',...
      'fontsize',9,'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.85 0.670 0.10 hght],...
      'string',str,'fontsize',9, 'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   
   str = num2str(length(top.trace_var.pts_restored));   
   uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.05 0.59 0.90 hght],...
      'string',['Number of points manually restored: '],...
      'fontsize',9,'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);   
  uicontrol(h_statbox,'style','text','Units','normalized',...
      'Position',[0.85 0.59 0.10 hght],...
      'string',str,'fontsize',9, 'HorizontalAlignment','left',...
      'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]); 
   
   if strcmp(top.local_use,'no')   
      str = num2str(top.trace_var.stats.numpts.outsideMax);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.51 0.90 hght],...
         'string',['Number of points outside maximum bound: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.51 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.outsideMin);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.43 0.85 hght],...
         'string',['Number of points outside minimum bound: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.43 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.despiked);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.35 0.85 hght],...
         'string',['Number of points Despiked: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.35 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.clampedMax);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.27 0.85 hght],...
         'string',['Number of points outside upper clamp: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.27 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.clampedMin);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.19 0.85 hght],...
         'string',['Number of points outside lower clamp: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.19 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.outsideFilter);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.11 0.85 hght],...
         'string',['Number of points outside mean & std filter: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.11 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      
      str = num2str(top.trace_var.stats.numpts.dependCleaned);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.05 0.03 0.85 hght],...
         'string',['Number of dependent points removed: '],...
         'fontsize',9,'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
      uicontrol(h_statbox,'style','text','Units','normalized',...
         'Position',[0.85 0.03 0.10 hght],...
         'string',str,'fontsize',9, 'HorizontalAlignment','left',...
         'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);
   end
   
   set(h_statbox,'CloseRequestFcn','ta_statsmenu(''close_stats'')');
   top.h_statbox = h_statbox;
case 'close_stats'
   delete(top.h_statbox);
   top.h_statbox = [];
case 'curr_pts' 
   chck = [];
   if ~isempty(top.trace_var.pts_removed)
      pts(1).ind = intersect(top.x_data,top.trace_var.pts_removed);
      if ~isempty(pts(1).ind)
         chck = 1;
         pts(1).typeClean = 'Manually Removed';
      end
   end
   if ~isempty(top.trace_var.pts_restored)
      pts(2).ind = intersect(top.x_data,top.trace_var.pts_restored);
      if ~isempty(pts(2).ind)
         chck = [chck 2];
         pts(2).typeClean = 'Manually Restored';
      end      
   end   
   if strcmp(top.local_use, 'no')
      fldname = fieldnames(top.trace_var.stats.index);
      for i=1:length(fldname)
         switch char(fldname(i))    
         case 'PtsOutsideMin'
            fldind =3;
            typeClean = 'Outside Minimum';
         case 'PtsOutsideMax'
            fldind =4;
            typeClean = 'Outside Maximum';
         case 'PtsDespiked'
            fldind =5;
            typeClean = 'Single Despike';
         case 'PtsClampedMin'
            fldind =6;
            typeClean = 'Clamped Minimum';
         case 'PtsClampedMax'
            fldind =7;
            typeClean = 'Clamped Maximum';
         case 'PtsDependClean'
            fldind =8;
            typeClean = 'Dependent';
         case 'PtsFiltered'
            fldind =9;
            typeClean = 'Filter Envelope';
         otherwise
            fldind = [];
            typeClean = [];
         end 
         if ~isempty(fldind)
            temp = getfield(top.trace_var.stats.index,char(fldname(i)));
            if ~isempty(temp)
               pts(fldind).ind = intersect(top.x_data,temp);
               pts(fldind).typeClean = typeClean;
               if ~isempty(pts(fldind).ind)
                  chck = [chck fldind];
               end
            end         
         end      
      end 
   end
   
   pos = [450 200 300 200];    
   if ~isempty(top.h_selectedStats)& ishandle(top.h_selectedStats)
      pos = get(top.h_selectedStats, 'Position');
      delete(top.h_selectedStats);
   end     
   h_selectedStats = figure('handlevisibility','off','IntegerHandle','off',...
      'NumberTitle','off','MenuBar','none','color',[0 0 0],...
      'Position',pos,'Name','Stats of Selected Points');       
    
   top.h_selectedStats = h_selectedStats;
   
   if ~isempty(chck)
      wp = [0.1 0.85 0.85 .1];
      tp = [0.65 0.85 0.30 .1];
      for i=chck
         tmpStr = length(pts(i).ind);
         if tmpStr > 1
            str = ['NUM: 'num2str(tmpStr)];
         else
            str = ['DOY:  'num2str(top.trace_var.DOY(pts(i).ind))];
         end          
         uicontrol(h_selectedStats,'style','text','Units','normalized',...
            'Position',wp,...
            'string',pts(i).typeClean,...
            'fontsize',9, 'HorizontalAlignment','left',...
            'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);    
         uicontrol(h_selectedStats,'style','text','Units','normalized',...
            'Position',tp,...
            'string',str,...
            'fontsize',9, 'HorizontalAlignment','left',...
            'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);       
         wp(2) = wp(2) - 0.1;
         tp(2) = tp(2) - 0.1;
      end
   end
end

set(gca,'UserData',top);
