function warn_message(str)
%simple warning message 
fig_msg = figure('handlevisibility','off','IntegerHandle','off',...
   'NumberTitle','off','MenuBar','none','Position',[200 300 400 100],...
   'Name','WARNING','color',[.85 .85 .85],'Tag','WarnMsg');
h = uicontrol(fig_msg,'style','text','units','normalized','position',[.01 .50 .98 .50],...
      'string',str,'fontsize',12,'backgroundcolor',[.85 .85 .85]);   
