function recalc_create(SiteId,Years,base_path,dir_name)

%==========================================================================
% Create base directory 
% If it already exists stop because it might already be in use. If user
% wants to use this name it'll have to be deleted manually.
[s,mes] = mkdir(base_path,dir_name);
if ~isempty(mes)
    disp(mes);
    disp('... returning');
    return
end

base_dir = fullfile(base_path,dir_name);

%==========================================================================
% Start log file
diary(fullfile(base_dir,'recalc.log'));
disp(sprintf('== Creating recalculation setup =='));
disp(sprintf('Date: %s',datestr(now)));
disp(sprintf('SiteId = %s',SiteId));

%==========================================================================
% Copy and create biomet setup matlab files
disp('Copying biomet.net...');
[s,mes] = mkdir(base_dir,'Biomet.net\Matlab');
[s,mes] = copyfile('\\paoa001\matlab',[base_dir '\Biomet.net\Matlab']);
if ~isempty(mes)
    disp(mes)
    disp('... returning');
    return
else
    disp(sprintf('%s - done',datestr(now)));
end

disp('Copying Site_specific...');
All_Sites     = {'BS'   'CR' 'FEN' 'HJP02' 'HJP75' 'JP'   'OY' 'PA'   'YF'};
All_Site_name = {'PAOB' 'CR' 'FEN' 'HJP02' 'HJP75' 'PAOJ' 'OY' 'PAOA' 'YF'};
[dum,ind_id] = intersect(All_Sites,upper(SiteId));
SiteName = char(All_Site_name(ind_id));

[s,mes] = mkdir(base_dir,'UBC_PC_SETUP\Site_specific');
[s,mes] = copyfile(['\\paoa001\Sites\' SiteName '\UBC_PC_SETUP\Site_specific\*.m'],[base_dir '\UBC_PC_SETUP\Site_specific']);
% PC_specific is not copied since we use the one on the current PC
if ~isempty(mes)
    disp(mes)
    disp('... returning');
    return
else
    disp(sprintf('%s - done',datestr(now)));
end

disp('Creating fr_get_local_path.m...');
% if on the network overwrite fr_get_local_path
fid = fopen([base_dir '\UBC_PC_SETUP\Site_specific\fr_get_local_path.m'],'wt');
if fid > 0
    fprintf(fid,'%s\n','function [dataPth,hhourPth,databasePth,csiPth] = FR_get_local_path');
    fprintf(fid,'%% This function was generated by recalc_create.m\n');
    fprintf(fid,'dataPth  = %s%s%s;\n',39,['\\FLUXNET02\HFREQ_' upper(SiteId) '\met-data\data\'],39);
    fprintf(fid,'hhourPth  = %s%s%s;\n',39,fullfile(base_dir,'\hhour\') ,39);
    fprintf(fid,'databasePth  = %s%s%s;\n',39,'\\ANNEX001\Database\',39);
    fprintf(fid,'csiPth  = %s%s%s;\n',39,['\\FLUXNET02\HFREQ_' upper(SiteId) '\met-data\csi_net\'],39);
    fclose(fid);
else
    disp(['Could not create ' base_dir '\UBC_PC_SETUP\Site_specific\fr_get_local_path.m'])
    disp('... returning');
    return
end
disp(sprintf('%s - done',datestr(now)));

disp('Copying calibration files...');
[s,mes] = mkdir(base_dir,'hhour');
[s,mes] = copyfile(['\\paoa001\Sites\' SiteName '\hhour\calibrations*.*'],[base_dir '\hhour']);
if ~isempty(mes)
    disp(mes)
    disp('... returning');
    return
else
    disp(sprintf('%s - done',datestr(now)));
end

%==========================================================================
% Create first, second and thirdstage database (for comparison with current
% results)
disp('Creating first, second and third stage database ...');
[s,mes] = mkdir(base_dir,'database');
pth = pwd;
cd(base_dir); % This causes the cleaning log file to be created in base_dir
for k=1:length(Years)
    try
        fr_automated_cleaning(Years(k),SiteId,[1 2 3],[base_dir '\database'])
    catch
        disp(['Cleaned traces backup failed for ' SiteId ', ' num2str(Years(k)) ]);
        continue
    end
end
cd(pth);
diary(fullfile(base_dir,'recalc.log'));
disp(sprintf('== Finished recalculation setup =='));

return

