function select_datapoints(axis_hndl)
%
%-----------------------------------------------------------------------
% select datapoints from a subplot by mouseclick 
% (one point per mouseclick, end input by hitting 'enter')
% output index of data points -> use to mark same datapoints 
% in other subplot
%
% functionality: select datapoints, unselect all/last points 
% that are selected in the current window.
%
% procedure is defined in context_select_datapoints
% created 10 July 2002, natascha kljun
%
%-----------------------------------------------------------------------

% Define the menu:

ax_menu = uicontextmenu;
set(axis_hndl,'UIContextMenu', ax_menu);
c_select = uimenu(ax_menu,...
   'Label', 'Select Point',...
   'Callback', 'context_select_datapoints(''select_point'')');
c = uimenu(ax_menu,...
   'Label','UnSelect Last Point',...
   'Callback','context_select_datapoints(''unselect_last'')');
c = uimenu(ax_menu,...
   'Label','UnSelect All Points',...
   'Callback','context_select_datapoints(''unselect_all'')');
c = uimenu(ax_menu,...
   'Label','View HF data',...
   'Callback','context_select_datapoints(''view_hf'')');
c = uimenu(ax_menu,...
   'Label','View time series',...
   'Callback','context_select_datapoints(''view_time_series'')',...
   'Enable','on',...
   'Tag','uim_ts');
c = uimenu(ax_menu,...
   'Label', 'View regressions',...
   'Callback','context_select_datapoints(''view_regression'')',...
   'Enable','off',...
   'Tag','uim_reg');

hndls = [ax_menu];