function test_variable_names_in_structure(trc,stage)
% Check which names are missing the trc structure for stage 'stage'

names_to_be = var_names(stage);

names_missing = setdiff(names_to_be,{trc(:).variableName}');

if stage == 2
   stage_str = 'Second Stage';
else
   stage_str = 'Third Stage';
end    

if isempty(names_missing)
   disp(['This trace structure contains all variables required in ' stage_str ' cleaning.']);
else
   disp([stage_str ' names missing in this trace structure:']);
   disp(' ');
   for i = 1:length(names_missing)
      disp(char(names_missing(i)));
   end
end

function names = var_names(stage)

names_second_stage = ...
{'air_temperature_main',...
'relative_humidity_main',...
'barometric_pressure_main',...
'wind_direction_main',...
'wind_speed_cup_main',...
'wind_speed_3D_main',...
'precipitation_cumulative',...
'precipitation',...
'co2_avg_main',...
'h2o_avg_main',...
'radiation_downwelling_potential',...
'radiation_net_main',...
'ppfd_downwelling_main',...
'ppfd_upwelling_main',...
'ppfd_absorbed',...
'global_radiation_main',...
'shortwave_radiation_upwelling_main',...
'longwave_radiation_downwelling_main',...
'longwave_radiation_upwelling_main',...
'soil_temperature_main',...
'soil_moisture_main',...
'soil_heat_flux_main',...
'ustar_main',...
'le_main',...
'h_main',...
'fc_main',...
'energy_storage_main',...
'co2_storage_one_level_main',...
'co2_storage_main',...
'nee_main',...
'zeta',...
'aerodynamic_resistance_momentum',...
'aerodynamic_resistance_scalar',...
'surface_conductance',...
'canopy_wet_flag',...
'canopy_dry_flag'};

if stage == 2
    names = names_second_stage';
    return
else
    names_third_stage_only = ...
        {'le_mdv_main',...
            'eco_respiration_fitted',...
            'eco_photosynthesis_fitted',...
            'nep_fitted',...
            'eco_respiration_measured',...
            'eco_photosynthesis_measured',...
            'eco_respiration_filled_with_fits',...
            'eco_photosynthesis_filled_with_fits',...
            'nep_filled_with_fits'};
    names = [names_second_stage'; names_third_stage_only'];
end