function view_hf_spec(fig)
%last change: 04.06.2003 nk

% Extract the data for variable 1 & 2
user_data_in = get(fig,'UserData');
currentDate  = user_data_in(1).currentDate;

for i = 1:6
   data(:,i)         = user_data_in(i).data;
end

titles       = [user_data_in(:).title];
units        = [user_data_in(:).unit];
string1		 = [user_data_in(:).string1];

% get the selected traces from popup menu
for i = 1:2
   a      = ['Trace' num2str(i)'];
   b      = findobj(fig,'Tag',a);            % get the selected trace from popup menu
   val(i) = get(b,'Value');                 % read the string matrix
end


% Configuration of spectral calc:
config_info.Spectra.Fs				= user_data_in(1).Fs;
config_info.Spectra.nfft			= 2^15;
config_info.Spectra.n_spec			= 2^15/2+1;
config_info.Spectra.csdVec       = [1 2 3 4 5 6];
config_info.Spectra.psdVec       = [1 2 3 4 5 6];
config_info.Spectra.csdRef       = 3;
config_info.Spectra.no_spec_bins	= 100;
config_info.Spectra.no_in_bin		= 1;
config_info.Spectra.filtX			= 'hamming';
config_info.Spectra.dflag        = 'linear';

[Flog,len_spec_bins,spec_bins] = fr_config_spec(config_info.Spectra.no_spec_bins,...
      config_info.Spectra.no_in_bin,config_info.Spectra.nfft,config_info.Spectra.Fs);

spec_info.no_spec_bins	= 100;
spec_info.Flog				= Flog;
spec_info.len_spec_bins	= len_spec_bins;
spec_info.spec_bins		= spec_bins;

[m,n] = size(data);
delays = ones(1,n); 
delays([5 6]) = [15 15];
Spectra = fr_calc_spectra(data,delays,config_info,spec_info);

% Assemble user_data for new figure
user_data.data 	= Spectra;
user_data.xdata 	= Flog;
user_data.type 	= 'spec';
user_data.titles  = titles(1:7);
user_data.units  	= units(1:7);
user_data.string1 = string1(1:7);

% Create title info
string2 = 'Spectra';

% get the Site from popup menu
e = findobj(fig,'Tag','Site');           
f = get(e,'String');                         
string3 = deblank([f]);

% get the selected traces from popup menu
for i = 1:2
   a      = ['Trace' num2str(i)'];
   b      = findobj(fig,'Tag',a);            % get the selected trace from popup menu
   val(i) = get(b,'Value');                 % read the string matrix
end

% get the Site from popup menu
e = findobj(fig,'Tag','Site');           
f = get(e,'String');                         
string3 = deblank([f]);

% get the Site from popup menu
cur_loc = currentDate-6/24;
cur_vec = datevec(cur_loc);
string4 = [datestr(cur_loc,1) ' (' num2str(floor(cur_loc)-datenum(cur_vec(1),1,0),'%3.0f') ') ' datestr(cur_loc,15)];

%background color
colordef black;
bgc = [0 0.36 0.532];

h0 = figure;
set(h0,'Units','normalized', ...
	'Color',bgc, ...
	'MenuBar','none', ...
	'Name','View Data', ...
	'NumberTitle','off', ...
	'Position',[0 0.01 1 0.9555], ...
   'ToolBar','none',...
   'UserData',user_data);

% frame control region
h1 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.72 0.0 0.001 1.0], ...
   'Style','frame');

% create title
h2 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.917 0.25 0.04], ...
   'String',string3, ...
   'Style','text', ...
   'Tag','Site');
h3 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.84 0.3 0.04], ...
   'String',string4, ...
   'Style','text', ...
   'Tag','Year');
h4 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.8785 0.3 0.04], ...
   'String',string2, ...
   'Style','text', ...
   'Tag','TitleData');

% menu with possible traces for plot 1
h5 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.77 0.2 0.05], ...
   'String','Variable 1', ...
   'Style','text');

h6 = uicontrol('Units','normalized', ...
   'BackgroundColor',[1 1 1], ...
   'FontSize',9, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[0 0 0],...
   'Position',[0.75 0.68 0.205 0.1], ...
   'String',user_data.string1, ...
   'Style','listbox', ...
   'Tag','Trace1',...
   'Value',val(1),...
   'ListboxTop',val(1));

% menu with possible traces for plot 2
h7 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.61 0.2 0.05], ...
   'String','Variable 2', ...
   'Style','text');

h9 = uicontrol('Units','normalized', ...
   'BackgroundColor',[1 1 1], ...
   'FontSize',9, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[0 0 0],...
   'Position',[0.75 0.52 0.205 0.1], ...
   'String',user_data.string1, ...
   'Style','listbox', ...
   'Tag','Trace2',...
   'Value',val(2),...
   'ListboxTop',val(2));

% button 'plot traces', call view_selected_data.m
h11 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
    'HorizontalAlignment', 'left', ...
 	'Callback','view_hf_xy(gcf);', ...
	'Position',[0.75 0.42 0.135 0.05], ...
	'String','Plot Variables', ...
	'Tag','Plot_button1');

% button 'back'
h12 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
    'HorizontalAlignment', 'left', ...
	'Callback','close', ...
	'Position',[0.89 0.42 0.065 0.05], ...
   'String','Back');


view_hf_xy(gcf);

return