function view_hf_menu(fig,SiteId,pth)
% VIEW_HF_MENU Plot high frequency data from any Biomet site
%
%   VIEW_HF_MENU(DATE,SITEID) plot the hhour (GMT time) for that site
%
%   If SITEID differs from FR_CURRENT_SITEID, FR_SET_SITE(SITEID,'NETWORK')
%   is run, otherwise the current setup is used.

% Based on Natascha's view_menu
% 
% kai* Oct 28, 2003
% 
% Revisions:

if ishandle(fig)
   user_data_in = get(fig,'UserData');
   currentDate = user_data_in.currentDate;
   SiteId      = user_data_in.SiteId;
   pth         = user_data_in.pth;
else
   currentDate = fig;
end

if ~strcmp(upper(SiteId),upper(fr_current_siteid))
   fr_set_site(SiteId,'network');
end

if currentDate < 0
   return
end

user_data = fr_read_raw(currentDate,SiteId);

% user_data.currentDate  	= currentDate;
% user_data.tv   			= Eddy_HF_data(1).tv;
% user_data.data 			= Eddy_HF_data(1).data;
% user_data.titles        = Eddy_HF_data(1).title;
% user_data.units         = Eddy_HF_data(1).unit;
% user_data.string1       = Eddy_HF_data(1).name;

N = length(user_data(1).data);

if N <= 1
   hh = msgbox(['Data for ' datestr(currentDate,0) ' not available'],'No data','error','modal');
   bgc = [0 0.36 0.532];
   set(hh,'Color',bgc);
%   return
   view_hf_data(fig);
end

%[meansSr,statsSr,angles] = fr_rotatn( ...
%   [mean(Eddy_HF_data(:,1:3))],cov(Eddy_HF_data));
%[Eddy_HF_data] = fr_rotatn_hf(Eddy_HF_data,angles);
%Eddy_HF_data = Eddy_HF_data(:,1:7);
      
string2 = 'HF Data ending';

% get the Site from popup menu
string3 = upper(SiteId);

% get the Site from popup menu
cur_loc = currentDate-FR_get_offsetGMT(SiteId)/24;
cur_vec = datevec(cur_loc);
string4 = [datestr(cur_loc,1) ' (' num2str(floor(cur_loc)-datenum(cur_vec(1),1,0),'%3.0f') ') ' datestr(cur_loc,15) ' local time'];
string5 = [datestr(currentDate,15) ' GMT'];

%background color
colordef black;
bgc = [0 0.36 0.532];

h0 = figure;
set(h0,'Units','normalized', ...
	'Color',bgc, ...
	'MenuBar','none', ...
	'Name','View Data', ...
	'NumberTitle','off', ...
	'Position',[0 0.01 1 0.9555], ...
   'ToolBar','none',...
   'UserData',user_data);

% define axes background color and get window background color vector
%whitebg(h0,[0 0.1 0.2])
%bgc = get(gcf,'color');

% frame control region
h1 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.72 0.0 0.001 1.0], ...
   'Style','frame');

% create title
h2 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.917 0.25 0.04], ...
   'String',string3, ...
   'Style','text', ...
   'Tag','Site');
h3 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.84 0.3 0.04], ...
   'String',string4, ...
   'Style','text', ...
   'Tag','Year');
h3a= uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.86 0.81 0.3 0.04], ...
   'String',string5, ...
   'Style','text', ...
   'Tag','GMT');
h4 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.8785 0.3 0.04], ...
   'String',string2, ...
   'Style','text', ...
   'Tag','TitleData');

% menu with possible traces for plot 1
h5 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.77 0.2 0.05], ...
   'String','Variable 1', ...
   'Style','text');

h6 = uicontrol('Units','normalized', ...
   'BackgroundColor',[1 1 1], ...
   'FontSize',9, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[0 0 0],...
   'Position',[0.75 0.68 0.205 0.1], ...
   'String',[user_data.string1], ...
   'Style','listbox', ...
   'Tag','Trace1',...
   'Value',3,...
   'ListboxTop',3);   

% menu with possible traces for plot 2
h7 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.61 0.2 0.05], ...
   'String','Variable 2', ...
   'Style','text');

h9 = uicontrol('Units','normalized', ...
   'BackgroundColor',[1 1 1], ...
   'FontSize',9, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[0 0 0],...
   'Position',[0.75 0.52 0.205 0.1], ...
   'String',[user_data.string1], ...
   'Style','listbox', ...
   'Tag','Trace2',...
   'Value',4,...
   'ListboxTop',4);   

% menu with possible traces for plot 3
h10 = uicontrol('Units','normalized', ...
   'BackgroundColor',bgc, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[1 1 1],...
   'Position',[0.75 0.45 0.2 0.05], ...
   'String','Variable 3', ...
   'Style','text');

h12 = uicontrol('Units','normalized', ...
   'BackgroundColor',[1 1 1], ...
   'FontSize',9, ...
   'HorizontalAlignment', 'left', ...
   'ForegroundColor',[0 0 0],...
   'Position',[0.75 0.36 0.205 0.1], ...
   'String',[user_data.string1], ...
   'Style','listbox', ...
   'Tag','Trace3',...
   'Value',5,...
   'ListboxTop',5);   

% button 'plot traces', call view_selected_data.m
h11 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
    'HorizontalAlignment', 'left', ...
 	'Callback','view_hf_plt(gcf);', ...
	'Position',[0.75 0.275 0.135 0.05], ...
	'String','Plot Variables', ...
	'Tag','Plot_button1');

h12 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
    'HorizontalAlignment', 'left', ...
	'Callback','close', ...
	'Position',[0.89 0.275 0.065 0.05], ...
	'String','Back');

h13 = uicontrol('Parent',gcf, ...
   'Units','normalized', ...
   'BackgroundColor',[0.7 0.7 0.7], ...
   'HorizontalAlignment', 'left', ...
   'Callback','view_hf_xcorr(gcf)', ...
   'Position',[0.75 0.275-2*0.065 0.205 0.05], ...
   'String','Correlation',...
   'Enable','off',...
   'Tag','bt_corr');

h13 = uicontrol('Parent',gcf, ...
   'Units','normalized', ...
   'BackgroundColor',[0.7 0.7 0.7], ...
   'HorizontalAlignment', 'left', ...
   'Callback','view_hf_spec(gcf)', ...
	'Position',[0.75 0.275-3*0.065 0.205 0.05], ...
   'String','Corr. var1 x var2',...
   'String','Spectra',...
   'Enable','off',...
   'Tag','bt_spec');

h14 = uicontrol('Parent',gcf, ...
   'Units','normalized', ...
   'BackgroundColor',[0.7 0.7 0.7], ...
   'HorizontalAlignment', 'left', ...
   'Callback','view_hf_1to1(gcf)', ...
	'Position',[0.75 0.275-1*0.065 0.205 0.05], ...
   'String','Plot Var1 vs. Var2',...
   'Enable','off',...
   'Tag','bt_1to1');

view_hf_plt(gcf);
%view_hf_empty(gcf);

return
